- id: doi:10.48550/arXiv.2510.25497
  type: paper
  image: /images/research/r4rr.png
  publisher: NeurIPS
  description: Description
  buttons:
    - type: source
      text: Code
      link: https://github.com/Giotto-maker/r4rr


- id: doi:10.48550/arXiv.2502.18237
  type: paper
  image: /images/research/DRL.png
  description: We introduce the Disjunctive Refinement Layer (DRL), a novel layer designed to enforce the alignment of generated data with the background knowledge specified in user-defined constraints. DRL is the first method able to automatically make deep learning models inherently compliant with constraints as expressive as quantifier-free linear formulas, which can define non-convex and even disconnected spaces.
  publisher: ICLR
  buttons:
    - type: source
      text: Code
      link: https://github.com/mihaela-stoian/DRL_DGM


- id: doi:10.48550/arXiv.2508.21787
  type: paper
  image: /images/research/picsar.png
  description: Description
  publisher: preprint
  buttons:
    - type: source
      text: Code
      link: https://doi.org/10.48550/arXiv.2508.21787



- id: doi:10.48550/arXiv.2503.05954
  type: paper
  image: /images/research/survey_tab_synth.png
  description: "We review deep generative modelling approaches for tabular data from the perspective of four types of requirements: utility of the synthetic data, alignment of the synthetic data with domain-specific knowledge, statistical fidelity of the synthetic data distribution compared to the real data distribution, and privacy-preserving capabilities."
  publisher: preprint



- id: doi:10.48550/arXiv.2402.04823
  type: paper
  image: /images/research/dgm+ll.png
  publisher: ICLR
  description: We show how deep generative models for tabular data can be constrained such that their generated samples are guaranteed to be compliant with given constraints. This is achieved by automatically parsing the constraints and transforming them into a Constraint Layer seamlessly integrated with the model.
  buttons:
    - type: source
      text: Code
      link: https://github.com/mihaela-stoian/ConstrainedDGM


- id: doi:10.48550/arXiv.2409.12642
  type: paper
  image: /images/research/adv_gan.png
  description: We adapt popular tabular deep generative models into adversarial models and evaluate their effectiveness in generating realistic adversarial examples that conform to domain constraints.
  publisher: ICMLC
  buttons:
    - type: source
      text: Code
      link: https://github.com/salijona/C-AdvDGM


- id: doi:10.48550/arXiv.2402.18285
  type: paper
  image: /images/research/pishield_demo.png
  description: We introduce PiShield, the first package ever allowing for the integration of (propositional or linear) requirements into the neural networks’ topology. PiShield guarantees compliance with these requirements, regardless of input.
  publisher: IJCAI
  buttons:
    - type: source
      text: Code
      link: https://github.com/mihaela-stoian/PiShield
    - type: website
      text: Website
      link: https://sites.google.com/view/pishield/home
