- id: doi:10.48550/arXiv.2402.04823
  image: images/research/DRL.png
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  repo: mihaela-stoian/ConstrainedDGM

- id: doi:10.48550/arXiv.2502.18237
  type: paper
  image: images/research/DRL.png
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  publisher: ICLR
  buttons:
    - type: source
      text: Code
      link: https://github.com/mihaela-stoian/DRL_DGM

